---
- hosts: all
  become: true
  tasks:
  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: install apache2 package
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes

  - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"
